# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - techbudy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://myregstry112.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c92a0172b1be4386b02344f666b63045 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c654a923e1b24383ad841008ff41671f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: myregstry112.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c92a0172b1be4386b02344f666b63045 }}/mycustomeimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'techbudy'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c616be0aa6d849d3b7cc8e0faddd7620 }}
        images: 'myregstry112.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c92a0172b1be4386b02344f666b63045 }}/mycustomeimage:${{ github.sha }}'